# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Norsys
    url: https://www.norsys.fr
  - name: Daily
    url: https://norsys-daily.norsys.fr
  - name: Permaentreprise
    url: https://www.permaentreprise.fr
  - name: git
    url: https://git.norsys.fr
  - name: SiteInterne
    url: $SITE_CLIENT1
  - name: Norsys_DNS_Primaire
    check: "tcp-ping"
    url: ns1.norsys.fr
    port: 53
  - name: Norsys_DNS_Secondaire
    check: "tcp-ping"
    url: ns2.norsys.fr
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor"
  introMessage: En cas de problèmes nous contacter 
  navbar:
    - title: Status
      href: https://github.com/svasseur/uptime
    - title: Norsys
      href: https://www.norsys.fr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
