name: Post issues to Teams

on:
  issues:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify
        uses: davidwengier/PostAdaptiveCard@v1.0.4
        with:
          webhook_uri: "https://prod-44.westeurope.logic.azure.com:443/workflows/c3994e53d2b9435f8953a0bb6c4cf421/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=umQ7FJFJ61xce_uI6rR5_x48vyJqcstvdu7BJGBS0Ow"
