name: Post issues to Teams

on:
  issues:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify
        uses: davidwengier/PostAdaptiveCard@v1.0.4
        with:
          webhook-uri: <insert your webhook URI here>
